Repository paw-ong/pawong-frontend, pull requests merged in 2025-05, with the labels that each got.

#16 [PW-15] 상단바 헤더 반응형으로 수정했습니다.
  src/components/layout/Header.css
  src/components/layout/Header.jsx
  src/index.css
Labels: ✨ Feature

#17 [PW-14] 자동완성 구현
  src/components/pet/AdoptionSearchBar.css
  src/components/pet/AdoptionSearchBar.jsx
Labels: ✨ Feature

#12 [PW-5] 카카오 로그인 연동 및 추가 정보 저장 후 유저 정보 조회 API 연동
  .gitignore
  package-lock.json
  src/App.jsx
  src/api/client.js
  src/assets/images/info/phone.png
  src/assets/images/info/placeholder.png
  src/assets/images/info/user.png
  src/components/auth/OAuthRedirectHandler.jsx
  src/components/auth/RequireAuth.jsx
  src/components/layout/Header.css
  src/components/layout/Header.jsx
  src/contexts/AuthContext.jsx
  src/main.jsx
  src/pages/AdditionalInfo.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  vite.config.js
Labels: ✨ Feature

#21 [PW-20] 유기동물 찜 기능 및 찜 목록 조회 기능
  package-lock.json
  package.json
  src/assets/images/icons/arrow-left.svg
  src/assets/images/icons/arrow-right.svg
  src/components/mypage/FavoritesSlider.css
  src/components/mypage/FavoritesSlider.jsx
  src/components/pet/AdoptionResultList.jsx
  src/components/pet/PetCard.css
  src/components/pet/PetCard.jsx
  src/pages/MyPage.jsx
Labels: ✨ Feature

#27 [PW-13] 상세 보기 화면 구현 및 검색 시 지역 조건 추가
  src/App.jsx
  src/api/client.js
  src/assets/data/addr.json
  src/components/mypage/FavoritesSlider.jsx
  src/components/pet/AddressModal.css
  src/components/pet/AddressModal.jsx
  src/components/pet/AdoptionRecommendList.jsx
  src/components/pet/AdoptionResultList.jsx
  src/components/pet/AdoptionSearchBar.css
  src/components/pet/AdoptionSearchBar.jsx
  src/components/pet/PetCard.jsx
  src/pages/Adoption.jsx
  src/pages/AdoptionDetail.css
  src/pages/AdoptionDetail.jsx
  src/pages/MainPage.jsx
Labels: ✨ Feature, 🔨 Refactor

#28 [PW-26] 유기동물 검색 페이지 무한스크롤 key 속성 오류 및 헤더 입양동물 navigation 경로 변경
  src/components/layout/Header.jsx
  src/components/mypage/FavoritesSlider.jsx
  src/components/pet/AdoptionResultList.jsx
Labels: 🐞 BugFix

#30 [PW-29] 상세페이지 디자인 수정
  src/pages/AdoptionDetail.css
  src/pages/AdoptionDetail.jsx
Labels: 🔨 Refactor

#32 [PW-31] 찜 목록 kindNm 오류 수정
  src/components/mypage/FavoritesSlider.jsx
Labels: 🐞 BugFix

#34 [PW-33] 품종을 선택 안하면 전체로 검색되게 수정
  src/components/pet/AdoptionSearchBar.jsx
Labels: 🐞 BugFix

#36 [PW-35] Axios 응답 객체에 대해 에러 처리
  src/api/client.js
  src/components/auth/RequireAuth.jsx
  src/contexts/AuthContext.jsx
Labels: 🔨 Refactor
